version: '3.9'
services:

    nginx:
      build: requirements/nginx/
      container_name: nginx
      ports:
        - "443:443"
      volumes:
       - website:/var/www/html
      depends_on:
       - wordpress
      networks:
       - chilee_network
      restart: always

    wordpress:
      build: requirements/wordpress/
      container_name: wordpress
      expose:
        - "9000"
      volumes:
       - website:/var/www/html
      depends_on:
        - mariadb
        - redis
      networks:
        - chilee_network
      restart: always
      environment:
        MYSQL_HOST:       ${MYSQL_HOST}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
        DOMAIN_NAME:      ${DOMAIN_NAME}
        WP_TITLE:         ${WP_TITLE}
        WP_ADMIN_USR:     ${WP_ADMIN_USR}
        WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
        WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
        WP_USR:           ${WP_USR}
        WP_PWD:           ${WP_PWD}
        WP_EMAIL:         ${WP_EMAIL}
        REDIS_HOST:       ${REDIS_HOST}
        REDIS_PWD:        ${REDIS_PWD}

    mariadb:
      build: requirements/mariadb/
      container_name: mariadb
      expose:
        - "3306"
      volumes:
       - mariadb:/var/lib/mysql
      networks:
        - chilee_network
      restart: always
      environment:
        MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

    redis:
      build: requirements/bonus/redis
      container_name: redis
      expose:
        - "6379"
      volumes:
        - data_2:/data
      networks:
        - chilee_network
      restart: always
      environment:
        REDIS_PWD: ${REDIS_PWD}

    ftps:
      build: requirements/bonus/ftps
      container_name: ftps
      ports: 
        - "21:21"
        - "21100-21110:21100-21110"
      volumes:
       - website:/var/www/html
      networks:
        - chilee_network
      restart: always
      environment:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}

    portainer:
      image: portainer/portainer-ce
      container_name: portainer
      ports:
        - "8000:8000"
        - "9443:9443"
      restart: always
      security_opt:
        - no-new-privileges:true
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  chilee_network:

volumes:
  website:
    driver_opts:
      type: none
      device: /home/chilee/data/website
      o: bind

  mariadb:
    driver_opts:
      type: none
      device: /home/chilee/data/mariadb
      o: bind

  data_2:
    driver_opts:
      type: none
      device: /home/chilee/data/data_2
      o: bind

