version: '3'
services:

    nginx:
      build: requirements/nginx/
      image: nginx:stable-alpine
      container_name: nginx
      ports:
        - "443:443"
      volumes:
       - "/home/chilee/data/website:/var/www/html"
      depends_on:
       - wordpress
      networks:
       - chilee_network
      restart: always

    wordpress:
      build: requirements/wordpress/
      image: wordpress:5.7
      container_name: wordpress
      ports:
        - "9000:9000"
      volumes:
       - "/home/chilee/data/website:/var/www/html"
      depends_on:
        - mariadb
        - redis
      networks:
        - chilee_network
      restart: always
      environment:
        MYSQL_HOST:       ${MYSQL_HOST}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}
        DOMAIN_NAME:      ${DOMAIN_NAME}
        WP_TITLE:         ${WP_TITLE}
        WP_ADMIN_USR:     ${WP_ADMIN_USR}
        WP_ADMIN_PWD:     ${WP_ADMIN_PWD}
        WP_ADMIN_EMAIL:   ${WP_ADMIN_EMAIL}
        WP_USR:           ${WP_USR}
        WP_PWD:           ${WP_PWD}
        WP_EMAIL:         ${WP_EMAIL}
        REDIS_HOST:       ${REDIS_HOST}
        REDIS_PWD:        ${REDIS_PWD}

    mariadb:
      build: requirements/mariadb/
      image: mariadb:10.2
      container_name: mariadb
      ports:
        - "3306:3306"
      volumes:
       - "/home/chilee/data/mariadb:/var/lib/mysql"
      networks:
        - chilee_network
      restart: always
      environment:
        MYSQL_ROOT_PWD:   ${MYSQL_ROOT_PWD}
        WP_DATABASE_NAME: ${WP_DATABASE_NAME}
        WP_DATABASE_USR:  ${WP_DATABASE_USR}
        WP_DATABASE_PWD:  ${WP_DATABASE_PWD}

    redis:
      build: requirements/bonus/redis
      image: redis:v6.0
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - chilee_network
      restart: always
      environment:
        REDIS_PWD: ${REDIS_PWD}

    ftp-server:
      build: requirements/bonus/ftp-server
      image: vsftpd
      container_name: ftp-server
      ports: 
        - "21:21"
        - "21100-21110:21100-21110"
      volumes:
       - "/home/chilee/data/website:/var/www/html"
      networks:
        - chilee_network
      restart: always
      environment:
        FTP_USR: ${FTP_USR}
        FTP_PWD: ${FTP_PWD}
  
networks:
  chilee_network:


